// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAz5OskpPrvdHD5-mG1UdBo_rRtFpPCUMQ',
//     appId: '1:554525188818:web:7f6aead6f87b12508c430b',
//     messagingSenderId: '554525188818',
//     projectId: 'universe-abb43',
//     authDomain: 'universe-abb43.firebaseapp.com',
//     storageBucket: 'universe-abb43.appspot.com',
//     measurementId: 'G-X1JKN4YKK4',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBdilm6vDa2F0lBqBEx5FlrvfCBdOSyjnI',
//     appId: '1:554525188818:android:e92e4462ab958a438c430b',
//     messagingSenderId: '554525188818',
//     projectId: 'universe-abb43',
//     storageBucket: 'universe-abb43.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCOkwTdycQy6DUWmhq6J57UA9MG4_sBTLw',
//     appId: '1:554525188818:ios:1cf7330bceed98ce8c430b',
//     messagingSenderId: '554525188818',
//     projectId: 'universe-abb43',
//     storageBucket: 'universe-abb43.appspot.com',
//     iosBundleId: 'com.example.universe',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCOkwTdycQy6DUWmhq6J57UA9MG4_sBTLw',
//     appId: '1:554525188818:ios:a7f3cee5a9a7e92d8c430b',
//     messagingSenderId: '554525188818',
//     projectId: 'universe-abb43',
//     storageBucket: 'universe-abb43.appspot.com',
//     iosBundleId: 'com.example.universe.RunnerTests',
//   );
// }
