name: Count Dart Lines of Code

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  count-lines:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install cloc
      - name: Install cloc
        run: sudo apt-get install -y cloc

      # Count Dart lines of code
      - name: Count Dart lines
        run: |
          total_lines=$(cloc --include-lang=Dart . | grep 'Dart' | awk '{print $5}')
          echo "Total lines of Dart code: $total_lines"
          echo "dart_lines=$total_lines" >> $GITHUB_ENV

      # Output the result
      - name: Display the result
        run: echo "Total Dart lines of code: ${{ env.dart_lines }}"
